apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp
  labels:
    app: nginx-flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-flask
  template:
    metadata:
      labels:
        app: nginx-flask
    spec:
      containers:
      - name: testapp
        image: jbarosin/testapp 
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: testapp-entrypoint
spec:
  selector:
    app: nginx-flask 
  ports:
    - port: 80 
  type: LoadBalancer

